# .streamlit/secrets.toml

[mongo]
host = "localhost"
port = 27017
username = "xxx"
password = "xxx"

[neo4j]
uri = "neo4j+s://<your-neo4j-instance>.databases.neo4j.io"
user = "neo4j"
password = "your_password"
